laravel/app/Http/routes.php
<?php

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('projetos/sustentabilidade', 'ProjetosController@sustentabilidade')->name('projetos.sustentabilidade');
    Route::get('projetos/{categoria_slug?}', 'ProjetosController@index')->name('projetos');
    Route::get('projetos/{categoria_slug}/{projeto_slug}', 'ProjetosController@show')->name('projetos.show');
    Route::get('projetos22/{categoria_slug}/{projeto_slug}', 'ProjetosController@show22')->name('22-show');
    Route::get('midia', 'MidiaController@index')->name('midia');
    Route::get('sobre', 'SobreController@index')->name('sobre');
    Route::get('contato', 'ContatoController@index')->name('contato');
    Route::get('videos', 'VideoController@index')->name('videos');
    Route::post('contato', 'ContatoController@post')->name('contato.post');
    Route::get('politica-de-privacidade', 'PoliticaDePrivacidadeController@index')->name('politica-de-privacidade');
    Route::post('aceite-de-cookies', 'HomeController@postCookies')->name('aceite-de-cookies.post');

    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth']
    ], function() {
        Route::get('/', 'PainelController@index')->name('painel');

        /* GENERATED ROUTES */
		Route::resource('destaques', 'DestaquesController');
		Route::resource('imagens', 'ImagensController');
		Route::resource('home', 'HomeController', ['only' => ['index', 'update']]);
		Route::resource('midia', 'MidiaController');
		Route::get('midia/{midia}/imagens/clear', [
			'as'   => 'painel.midia.imagens.clear',
			'uses' => 'MidiaImagensController@clear'
		]);
		Route::resource('midia.imagens', 'MidiaImagensController', ['parameters' => ['imagens' => 'imagens_midia']]);
		Route::resource('sustentabilidade', 'SustentabilidadeController');
		Route::get('sustentabilidade/{sustentabilidade}/imagens/clear', [
			'as'   => 'painel.sustentabilidade.imagens.clear',
			'uses' => 'SustentabilidadeImagensController@clear'
		]);
		Route::resource('sustentabilidade.imagens', 'SustentabilidadeImagensController', ['parameters' => ['imagens' => 'imagens_sustentabilidade']]);
		Route::resource('projetos/categorias', 'ProjetosCategoriasController', ['parameters' => ['categorias' => 'categorias_projetos']]);
		Route::resource('projetos', 'ProjetosController');
		Route::get('projetos/{projetos}/imagens/clear', [
			'as'   => 'painel.projetos.imagens.clear',
			'uses' => 'ProjetosImagensController@clear'
		]);
		Route::resource('projetos.imagens', 'ProjetosImagensController', ['parameters' => ['imagens' => 'imagens_projetos']]);
		Route::resource('projetos.videos', 'ProjetosVideosController', ['parameters' => ['videos' => 'videos_projetos']]);
		Route::resource('banners', 'BannersController');
        Route::resource('videos', 'VideosController');
		Route::resource('sobre', 'SobreController', ['only' => ['index', 'update']]);
		Route::resource('configuracoes', 'ConfiguracoesController', ['only' => ['index', 'update']]);

        Route::get('contato/recebidos/{recebidos}/toggle', ['as' => 'painel.contato.recebidos.toggle', 'uses' => 'ContatosRecebidosController@toggle']);
        Route::resource('contato/recebidos', 'ContatosRecebidosController');
        Route::resource('contato', 'ContatoController');
        Route::resource('usuarios', 'UsuariosController');
        Route::resource('politica-de-privacidade', 'PoliticaDePrivacidadeController', ['only' => ['index', 'update']]);
        Route::get('aceite-de-cookies', 'AceiteDeCookiesController@index')->name('painel.aceite-de-cookies');


        Route::post('ckeditor-upload', 'PainelController@imageUpload');
        Route::post('order', 'PainelController@order');
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

        Route::get('generator', 'GeneratorController@index')->name('generator.index');
        Route::post('generator', 'GeneratorController@submit')->name('generator.submit');
    });

    // Auth
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function() {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');
        Route::post('login', 'AuthController@login')->name('login');
        Route::get('logout', 'AuthController@logout')->name('logout');
    });
});

laravel/app/Models/Projeto.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Helpers\CropImage;

use Cviebrock\EloquentSluggable\SluggableInterface;
use Cviebrock\EloquentSluggable\SluggableTrait;

class Projeto extends Model implements SluggableInterface
{
    use SluggableTrait;

    protected $sluggable = [
        'build_from' => 'titulo',
        'save_to'    => 'slug',
        'on_update'  => true
    ];

    protected $table = 'projetos';

    protected $guarded = ['id'];

    public function scopeOrdenados($query)
    {
        return $query->orderBy('ordem', 'ASC')->orderBy('id', 'DESC');
    }

    public function scopeCategoria($query, $categoria_id)
    {
        return $query->where('projetos_categoria_id', $categoria_id);
    }

    public function categoria()
    {
        return $this->belongsTo('App\Models\ProjetoCategoria', 'projetos_categoria_id');
    }

    public function imagens()
    {
        return $this->hasMany('App\Models\ProjetoImagem', 'projeto_id')->ordenados();
    }

    public function videos()
    {
        return $this->hasMany('App\Models\ProjetoVideo', 'projeto_id')->ordenados();
    }

    public static function upload_capa()
    {
        return CropImage::make('capa', [
            'width'  => 420,
            'height' => 420,
            'path'   => 'assets/img/projetos/'
        ]);
    }
}

laravel/app/Models/Videos.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Helpers\CropImage;

class Videos extends Model
{
    protected $table = 'videos';

    protected $guarded = ['id'];

    public function scopeOrdenados($query)
    {
        return $query->orderBy('ordem', 'ASC')->orderBy('id', 'DESC');
    }
}

laravel/app/Http/Controllers/Painel/ProjetosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ProjetosRequest;
use App\Http\Controllers\Controller;

use App\Models\Projeto;
use App\Models\ProjetoCategoria;

class ProjetosController extends Controller
{
    private $categorias;

    public function __construct()
    {
        $this->categorias = ProjetoCategoria::ordenados()->lists('titulo', 'id');
    }

    public function index(Request $request)
    {
        $categorias = $this->categorias;
        $filtro     = $request->query('filtro');

        if (ProjetoCategoria::find($filtro)) {
            $registros = Projeto::where('projetos_categoria_id', $filtro)->ordenados()->get();
        } else {
            $registros = Projeto::leftJoin('projetos_categorias as cat', 'cat.id', '=', 'projetos_categoria_id')
                ->orderBy('cat.ordem', 'ASC')
                ->orderBy('cat.id', 'DESC')
                ->select('projetos.*')
                ->ordenados()->get();
        }

        return view('painel.projetos.index', compact('categorias', 'registros', 'filtro'));
    }

    public function create()
    {
        $categorias = $this->categorias;

        return view('painel.projetos.create', compact('categorias'));
    }

    public function store(ProjetosRequest $request)
    {
        try {

            $input = $request->all();

            if (isset($input['capa'])) $input['capa'] = Projeto::upload_capa();

            Projeto::create($input);

            return redirect()->route('painel.projetos.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Projeto $registro)
    {
        $categorias = $this->categorias;

        return view('painel.projetos.edit', compact('registro', 'categorias'));
    }

    public function update(ProjetosRequest $request, Projeto $registro)
    {
        try {

            $input = $request->all();

            if (isset($input['capa'])) $input['capa'] = Projeto::upload_capa();

            $registro->update($input);

            return redirect()->route('painel.projetos.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Projeto $registro)
    {
        try {

            $registro->delete();

            return redirect()->route('painel.projetos.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/Painel/VideosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\VideosRequest;
use App\Http\Controllers\Controller;

use App\Models\Videos;

class VideosController extends Controller
{
    public function index()
    {
        $registros = Videos::ordenados()->get();

        return view('painel.videos.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.videos.create');
    }

    public function store(VideosRequest $request)
    {
        try {

            $input = $request->all();

            Videos::create($input);

            return redirect()->route('painel.videos.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Videos $registro)
    {
        return view('painel.videos.edit', compact('registro'));
    }

    public function update(VideosRequest $request, Videos $registro)
    {
        try {

            $input = $request->all();

            $registro->update($input);

            return redirect()->route('painel.videos.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Videos $registro)
    {
        try {

            $registro->delete();

            return redirect()->route('painel.videos.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/ProjetosController.php
<?php

namespace App\Http\Controllers;

use App\Models\Imagem;
use App\Models\ProjetoCategoria;
use App\Models\Projeto;
use App\Models\ProjetoImagem;
use App\Models\Sustentabilidade;

class ProjetosController extends Controller
{
    public function __construct()
    {
        view()->share('categorias', ProjetoCategoria::ordenados()->get());
    }

    public function index(ProjetoCategoria $categoria)
    {
        if (! $categoria->exists) {
            $categoria = ProjetoCategoria::ordenados()->firstOrFail();
        }

        view()->share('categoria', $categoria);

        $projetos = $categoria->projetos;

        return view('frontend.projetos.index', compact('projetos'));
    }

    // public function show(ProjetoCategoria $categoria, Projeto $projeto)
    // {
    //     if ($projeto->categoria->id != $categoria->id) {
    //         abort('404');
    //     }

    //     view()->share('categoria', $categoria);


    //     $nextKey = null;
    //     $projetos = $categoria->projetos;
    //     foreach ($projetos as $key => $value) {
    //         if ($value->id == $projeto->id) {
    //             $nextKey = $key + 1;
    //         }
    //     }

    //     $next = $projetos->get($nextKey);

    //     return view('frontend.projetos.show', compact('projeto', 'next'));
    // }

    public function show(ProjetoCategoria $categoria, Projeto $projeto)
    {
        if ($projeto->categoria->id != $categoria->id) {
            abort('404');
        }

        view()->share('categoria', $categoria);


        $nextKey = null;
        $projetos = $categoria->projetos;
        $imagemFirst = ProjetoImagem::where('projeto_id', $projeto->id)->first();
        
        foreach ($projetos as $key => $value) {
            if ($value->id == $projeto->id) {
                $nextKey = $key + 1;
            }
        }

        $next = $projetos->get($nextKey);

        return view('frontend.projetos.show', compact('projeto', 'next', 'imagemFirst'));
    }


    public function sustentabilidade()
    {
        $projetos = Sustentabilidade::ordenados()->paginate(6);

        if (request()->wantsJson()) {
            return response()->json([
                'view' => view('frontend.projetos.sustentabilidade._projetos', compact('projetos'))->render(),
                'next' => $projetos->nextPageUrl(),
            ]);
        }

        if (request()->has('page')) abort('404');

        return view('frontend.projetos.sustentabilidade.index', compact('projetos'));
    }
}

laravel/app/Http/Controllers/VideoController.php
<?php

namespace App\Http\Controllers;

use App\Models\Videos;

class VideoController extends Controller
{
    public function index()
    {
        $videos = Videos::ordenados()->get();

        return view('frontend.videos', compact('videos'));
    }
}

laravel/resources/views/painel/projetos/videos/create.blade.php
@extends('painel.common.template')

@section('content')

    <legend>
        <h2><small>Projetos / {{ $projeto->titulo }} /</small> Adicionar Vídeo</h2>
    </legend>

    {!! Form::open(['route' => ['painel.projetos.videos.store', $projeto->id]]) !!}

        @include('painel.projetos.videos.form', ['submitText' => 'Inserir'])

    {!! Form::close() !!}

@endsection

laravel/resources/views/painel/projetos/videos/edit.blade.php
@extends('painel.common.template')

@section('content')

    <legend>
        <h2><small>Projetos / {{ $projeto->titulo }} /</small> Editar Vídeo</h2>
    </legend>

    {!! Form::model($registro, [
        'route'  => ['painel.projetos.videos.update', $projeto->id, $registro->id],
        'method' => 'patch'])
    !!}

    @include('painel.projetos.videos.form', ['submitText' => 'Alterar'])

    {!! Form::close() !!}

@endsection

laravel/resources/views/painel/projetos/videos/form.blade.php
@include('painel.common.flash')

<div class="form-group">
    {!! Form::label('titulo', 'Título') !!}
    {!! Form::text('titulo', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('video', 'URL de incorporação do Vídeo (exemplo: https://www.youtube.com/embed/WbAEhGG5SpM)') !!}
    {!! Form::text('video', null, ['class' => 'form-control']) !!}
</div>

{!! Form::submit($submitText, ['class' => 'btn btn-success']) !!}

<a href="{{ route('painel.projetos.videos.index', $projeto->id) }}" class="btn btn-default btn-voltar">Voltar</a>

laravel/resources/views/painel/projetos/videos/index.blade.php
@extends('painel.common.template')

@section('content')

    @include('painel.common.flash')

    <a href="{{ route('painel.projetos.index') }}" title="Voltar para Projetos" class="btn btn-sm btn-default">
        &larr; Voltar para Projetos    </a>

    <legend>
        <h2>
            <small>Projetos / {{ $projeto->titulo }} /</small> Vídeos

            <a href="{{ route('painel.projetos.videos.create', $projeto->id) }}" class="btn btn-success btn-sm pull-right"><span class="glyphicon glyphicon-plus" style="margin-right:10px;"></span>Adicionar Vídeo</a>
        </h2>
    </legend>

    @if(!count($registros))
    <div class="alert alert-warning" role="alert">Nenhum registro encontrado.</div>
    @else
    <table class="table table-striped table-bordered table-hover table-sortable" data-table="projetos_videos">
        <thead>
            <tr>
                <th>Ordenar</th>
                <th>Título</th>
                <th><span class="glyphicon glyphicon-cog"></span></th>
            </tr>
        </thead>

        <tbody>
        @foreach ($registros as $registro)
            <tr class="tr-row" id="{{ $registro->id }}">
                <td>
                    <a href="#" class="btn btn-info btn-sm btn-move">
                        <span class="glyphicon glyphicon-move"></span>
                    </a>
                </td>
                <td>{{ $registro->titulo }}</td>
                <td class="crud-actions">
                    {!! Form::open(array('route' => array('painel.projetos.videos.destroy', $projeto->id, $registro->id), 'method' => 'delete')) !!}

                    <div class="btn-group btn-group-sm">
                        <a href="{{ route('painel.projetos.videos.edit', [$projeto->id, $registro->id]) }}" class="btn btn-primary btn-sm pull-left">
                            <span class="glyphicon glyphicon-pencil" style="margin-right:10px;"></span>Editar
                        </a>

                        <button type="submit" class="btn btn-danger btn-sm btn-delete"><span class="glyphicon glyphicon-remove" style="margin-right:10px;"></span>Excluir</button>
                    </div>

                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
    @endif

@endsection