laravel/app/Http/routes.php
<?php

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('projetos/sustentabilidade', 'ProjetosController@sustentabilidade')->name('projetos.sustentabilidade');
    Route::get('projetos/{categoria_slug?}', 'ProjetosController@index')->name('projetos');
    Route::get('projetos/{categoria_slug}/{projeto_slug}', 'ProjetosController@show')->name('projetos.show');
    Route::get('projetos22/{categoria_slug}/{projeto_slug}', 'ProjetosController@show22')->name('22-show');
    Route::get('midia', 'MidiaController@index')->name('midia');
    Route::get('sobre', 'SobreController@index')->name('sobre');
    Route::get('contato', 'ContatoController@index')->name('contato');
    Route::get('videos', 'VideoController@index')->name('videos');
    Route::post('contato', 'ContatoController@post')->name('contato.post');
    Route::get('politica-de-privacidade', 'PoliticaDePrivacidadeController@index')->name('politica-de-privacidade');
    Route::post('aceite-de-cookies', 'HomeController@postCookies')->name('aceite-de-cookies.post');

    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth']
    ], function() {
        Route::get('/', 'PainelController@index')->name('painel');

        /* GENERATED ROUTES */
		Route::resource('destaques', 'DestaquesController');
		Route::resource('imagens', 'ImagensController');
		Route::resource('home', 'HomeController', ['only' => ['index', 'update']]);
		Route::resource('midia', 'MidiaController');
		Route::get('midia/{midia}/imagens/clear', [
			'as'   => 'painel.midia.imagens.clear',
			'uses' => 'MidiaImagensController@clear'
		]);
		Route::resource('midia.imagens', 'MidiaImagensController', ['parameters' => ['imagens' => 'imagens_midia']]);
		Route::resource('sustentabilidade', 'SustentabilidadeController');
		Route::get('sustentabilidade/{sustentabilidade}/imagens/clear', [
			'as'   => 'painel.sustentabilidade.imagens.clear',
			'uses' => 'SustentabilidadeImagensController@clear'
		]);
		Route::resource('sustentabilidade.imagens', 'SustentabilidadeImagensController', ['parameters' => ['imagens' => 'imagens_sustentabilidade']]);
		Route::resource('projetos/categorias', 'ProjetosCategoriasController', ['parameters' => ['categorias' => 'categorias_projetos']]);
		Route::resource('projetos', 'ProjetosController');
		Route::get('projetos/{projetos}/imagens/clear', [
			'as'   => 'painel.projetos.imagens.clear',
			'uses' => 'ProjetosImagensController@clear'
		]);
		Route::resource('projetos.imagens', 'ProjetosImagensController', ['parameters' => ['imagens' => 'imagens_projetos']]);
		Route::resource('projetos.videos', 'ProjetosVideosController', ['parameters' => ['videos' => 'videos_projetos']]);
		Route::resource('banners', 'BannersController');
        Route::resource('videos', 'VideosController');
		Route::resource('sobre', 'SobreController', ['only' => ['index', 'update']]);
		Route::resource('configuracoes', 'ConfiguracoesController', ['only' => ['index', 'update']]);

        Route::get('contato/recebidos/{recebidos}/toggle', ['as' => 'painel.contato.recebidos.toggle', 'uses' => 'ContatosRecebidosController@toggle']);
        Route::resource('contato/recebidos', 'ContatosRecebidosController');
        Route::resource('contato', 'ContatoController');
        Route::resource('usuarios', 'UsuariosController');
        Route::resource('politica-de-privacidade', 'PoliticaDePrivacidadeController', ['only' => ['index', 'update']]);
        Route::get('aceite-de-cookies', 'AceiteDeCookiesController@index')->name('painel.aceite-de-cookies');


        Route::post('ckeditor-upload', 'PainelController@imageUpload');
        Route::post('order', 'PainelController@order');
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

        Route::get('generator', 'GeneratorController@index')->name('generator.index');
        Route::post('generator', 'GeneratorController@submit')->name('generator.submit');
    });

    // Auth
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function() {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');
        Route::post('login', 'AuthController@login')->name('login');
        Route::get('logout', 'AuthController@logout')->name('logout');
    });
});

laravel/app/Http/Controllers/Painel/AceiteDeCookiesController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Models\AceiteDeCookies;

class AceiteDeCookiesController extends Controller
{
    public function index()
    {
        $registros = AceiteDeCookies::orderBy('created_at', 'DESC')->get();

        return view('painel.cookies.index', compact('registros'));
    }
}

laravel/app/Http/Controllers/Painel/BannersController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\BannersRequest;
use App\Http\Controllers\Controller;

use App\Models\Banner;

class BannersController extends Controller
{
    public function index()
    {
        $registros = Banner::ordenados()->get();

        return view('painel.banners.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.banners.create');
    }

    public function store(BannersRequest $request)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Banner::upload_imagem();

            Banner::create($input);

            return redirect()->route('painel.banners.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Banner $registro)
    {
        return view('painel.banners.edit', compact('registro'));
    }

    public function update(BannersRequest $request, Banner $registro)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Banner::upload_imagem();

            $registro->update($input);

            return redirect()->route('painel.banners.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Banner $registro)
    {
        try {

            $registro->delete();

            return redirect()->route('painel.banners.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/Painel/ConfiguracoesController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ConfiguracoesRequest;
use App\Http\Controllers\Controller;

use App\Models\Configuracoes;

class ConfiguracoesController extends Controller
{
    public function index()
    {
        $registro = Configuracoes::first();

        return view('painel.configuracoes.edit', compact('registro'));
    }

    public function update(ConfiguracoesRequest $request, Configuracoes $registro)
    {
        try {
            $input = $request->all();

            if (isset($input['imagem_de_compartilhamento'])) $input['imagem_de_compartilhamento'] = Configuracoes::upload_imagem_de_compartilhamento();

            $registro->update($input);

            return redirect()->route('painel.configuracoes.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/ContatoController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ContatoRequest;
use App\Http\Controllers\Controller;

use App\Models\Contato;

class ContatoController extends Controller
{
    public function index()
    {
        $contato = Contato::first();

        return view('painel.contato.index', compact('contato'));
    }

    public function update(ContatoRequest $request, Contato $contato)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Contato::uploadImagem();

            $contato->update($input);
            return redirect()->route('painel.contato.index')->with('success', 'Informações alteradas com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar informações: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/ContatosRecebidosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Models\ContatoRecebido;

class ContatosRecebidosController extends Controller
{
    public function index()
    {
        $contatosrecebidos = ContatoRecebido::orderBy('created_at', 'DESC')->get();

        return view('painel.contato.recebidos.index', compact('contatosrecebidos'));
    }

    public function show(ContatoRecebido $contato)
    {
        $contato->update(['lido' => 1]);

        return view('painel.contato.recebidos.show', compact('contato'));
    }

    public function destroy(ContatoRecebido $contato)
    {
        try {

            $contato->delete();
            return redirect()->route('painel.contato.recebidos.index')->with('success', 'Mensagem excluída com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir mensagem: '.$e->getMessage()]);

        }
    }

    public function toggle(ContatoRecebido $contato, Request $request)
    {
        try {

            $contato->update([
                'lido' => !$contato->lido
            ]);

            return redirect()->route('painel.contato.recebidos.index')->with('success', 'Mensagem alterada com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar mensagem: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/DestaquesController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\DestaquesRequest;
use App\Http\Controllers\Controller;

use App\Models\Destaque;
use App\Models\Projeto;

class DestaquesController extends Controller
{
    public function index()
    {
        $registros = Destaque::ordenados()->get();

        return view('painel.destaques.index', compact('registros'));
    }

    public function create()
    {
        $projetos = Projeto::orderBy('titulo')->lists('titulo', 'id');

        return view('painel.destaques.create', compact('projetos'));
    }

    public function store(DestaquesRequest $request)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Destaque::upload_imagem();

            Destaque::create($input);

            return redirect()->route('painel.destaques.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Destaque $registro)
    {
        $projetos = Projeto::orderBy('titulo')->lists('titulo', 'id');

        return view('painel.destaques.edit', compact('registro', 'projetos'));
    }

    public function update(DestaquesRequest $request, Destaque $registro)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Destaque::upload_imagem();

            $registro->update($input);

            return redirect()->route('painel.destaques.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Destaque $registro)
    {
        try {

            $registro->delete();

            return redirect()->route('painel.destaques.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/Painel/GeneratorController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use Illuminate\Support\Facades\Artisan;

class GeneratorController extends Controller
{
    public function index()
    {
        return view('painel.generator.index');
    }

    public function submit(Request $request)
    {
        $this->validate($request, [
            'type'         => 'required',
            'resourceName' => 'required',
            'unitName'     => 'required_if:type,default'
        ]);

        $type = $request->get('type');

        $parameters = [
            'resourceName' => $request->get('resourceName'),
            'fields'       => $request->get('fields'),
        ];

        if(!empty($request->get('campos_nome')[0])) {
            $fields = '';
            foreach ($request->get('campos_nome') as $key => $campo_nome) {
                $field = [
                    $campo_nome,
                    $request->get('campos_tipo')[$key],
                    $request->get('campos_validation')[$key]
                ];

                $field = implode(':', $field);

                if (array_key_exists($key+1, $request->get('campos_nome'))) {
                    $fields .= $field.',';
                } else {
                    $fields .= $field;
                }
            }

            if (!empty($request->get('fields'))) {
                $parameters['fields'] = $request->get('fields').','.$fields;
            } else {
                $parameters['fields'] = $fields;
            }
        }

        if ($type == 'default') {
            $parameters['unitName'] = $request->get('unitName');
            $parameters['--slug']   = $request->get('slug');

            if ($request->get('paginate')) {
                $parameters['--paginate'] = $request->get('paginate');
            }
            if ($request->get('sortable')) {
                $parameters['--sortable'] = true;
            }
            if ($request->get('gallery')) {
                $parameters['--gallery'] = true;
            }
            if ($request->get('categories')) {
                $parameters['--categories'] = true;
            }
            if ($request->get('tags')) {
                $parameters['--tags'] = true;
            }
        }

        if ($request->get('force')) {
            $parameters['--force'] = true;
        }

        try {

            Artisan::call('resource:'.$type, $parameters);
            $output = Artisan::output();

            return back()->with(compact('output'))->withInput();

        } catch (\Exception $e) {

            return back()->withErrors([$e->getMessage()])->withInput();

        }

    }
}

laravel/app/Http/Controllers/Painel/HomeController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\HomeRequest;
use App\Http\Controllers\Controller;

use App\Models\Home;

class HomeController extends Controller
{
    public function index()
    {
        $registro = Home::first();

        return view('painel.home.edit', compact('registro'));
    }

    public function update(HomeRequest $request, Home $registro)
    {
        try {
            $input = $request->all();

            if (isset($input['imagem_sobre_1'])) $input['imagem_sobre_1'] = Home::upload_imagem_sobre_1();
            if (isset($input['imagem_sobre_2'])) $input['imagem_sobre_2'] = Home::upload_imagem_sobre_2();

            $registro->update($input);

            return redirect()->route('painel.home.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/PainelController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use DB;
use App\Helpers\CropImage;

class PainelController extends Controller
{

    public function index()
    {
        return view('painel.home');
    }

    public function order(Request $request)
    {
        if (!$request->ajax()) return false;

        $data  = $request->input('data');
        $table = $request->input('table');

        for ($i = 0; $i < count($data); $i++) {
            DB::table($table)->where('id', $data[$i])->update(array('ordem' => $i + 1));
        }

        return json_encode($data);
    }

    private $image_config = [
        'width'  => 980,
        'height' => null,
        'upsize' => true,
        'path'   => 'assets/img/editor/'
    ];

    public function imageUpload(Request $request)
    {
        $validator = \Validator::make($request->all(), [
            'imagem' => 'image|required'
        ]);

        if ($validator->fails()) {
            $response = [
                'error'   => true,
                'message' => 'O arquivo deve ser uma imagem.'
            ];
        } else {
            $imagem   = CropImage::make('imagem', $this->image_config);
            $response = [
                'filepath' => asset($this->image_config['path'] . $imagem)
            ];
        }

        return response()->json($response);
    }
}

laravel/resources/views/painel/common/flash.blade.php
@if(session('success'))
   <div class="alert alert-block alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {!! session('success') !!}
    </div>
@endif

@if($errors->any())
    <div class="alert alert-block alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        @foreach($errors->all() as $error)
        {!! $error !!}<br>
        @endforeach
    </div>
@endif

laravel/resources/views/painel/common/header.blade.php
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url('/') }}">{{ config('app.name') }}</a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
            @include('painel.common.nav')

            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown @if(Tools::routeIs(['painel.usuarios*', 'painel.configuracoes*'])) active @endif">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <span class="glyphicon glyphicon-cog small" style="margin-right:3px"></span>
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li @if(Tools::routeIs('painel.configuracoes*')) class="active" @endif>
                            <a href="{{ route('painel.configuracoes.index') }}">Configurações</a>
                        </li>
                        <li @if(Tools::routeIs('painel.politica-de-privacidade*')) class="active" @endif>
                            <a href="{{ route('painel.politica-de-privacidade.index') }}" class="link-nav-painel">Política de Privacidade</a>
                        </li>
                        <li @if(Tools::routeIs('painel.aceite-de-cookies*')) class="active" @endif>
                            <a href="{{ route('painel.aceite-de-cookies') }}">Relatório de Cookies</a>
                        </li>
                        <li @if(Tools::routeIs('painel.usuarios*')) class="active" @endif>
                            <a href="{{ route('painel.usuarios.index') }}">Usuários</a>
                        </li>
                        <li><a href="{{ route('logout') }}">Logout</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

laravel/resources/views/painel/common/nav.blade.php
<ul class="nav navbar-nav">
    <li class="dropdown @if(Tools::routeIs([
        'painel.home*',
        'painel.imagens*',
        'painel.destaques*',
        ])) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Home
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li @if(Tools::routeIs('painel.home*')) class="active" @endif>
                <a href="{{ route('painel.home.index') }}">Home</a>
            </li>
            <li @if(Tools::routeIs('painel.imagens*')) class="active" @endif>
                <a href="{{ route('painel.imagens.index') }}">Imagens</a>
            </li>
            <li @if(Tools::routeIs('painel.destaques*')) class="active" @endif>
                <a href="{{ route('painel.destaques.index') }}">Destaques</a>
            </li>
        </ul>
    </li>
    <li @if(Tools::routeIs('painel.banners*')) class="active" @endif>
        <a href="{{ route('painel.banners.index') }}">Banners</a>
    </li>
	<li @if(Tools::routeIs('painel.projetos*')) class="active" @endif>
		<a href="{{ route('painel.projetos.index') }}">Projetos</a>
	</li>
    <li @if(Tools::routeIs('painel.sustentabilidade*')) class="active" @endif>
        <a href="{{ route('painel.sustentabilidade.index') }}">Sustentabilidade</a>
    </li>
    <li @if(Tools::routeIs('painel.midia*')) class="active" @endif>
        <a href="{{ route('painel.midia.index') }}">Mídia</a>
    </li>
    <li @if(Tools::routeIs('painel.videos*')) class="active" @endif>
        <a href="{{ route('painel.videos.index') }}">Vídeos</a>
    </li>
	<li @if(Tools::routeIs('painel.sobre*')) class="active" @endif>
		<a href="{{ route('painel.sobre.index') }}">Sobre</a>
	</li>
    <li class="dropdown @if(Tools::routeIs('painel.contato*')) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Contato
            @if($contatosNaoLidos >= 1)
            <span class="label label-success" style="margin-left:3px;">{{ $contatosNaoLidos }}</span>
            @endif
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li @if(Tools::routeIs('painel.contato.index')) class="active" @endif>
                <a href="{{ route('painel.contato.index') }}">Informações de Contato</a>
            </li>
            <li @if(Tools::routeIs('painel.contato.recebidos*')) class="active" @endif>
                <a href="{{ route('painel.contato.recebidos.index') }}">
                    Contatos Recebidos
                    @if($contatosNaoLidos >= 1)
                    <span class="label label-success" style="margin-left:3px;">{{ $contatosNaoLidos }}</span>
                    @endif
                </a>
            </li>
        </ul>
    </li>
</ul>

laravel/resources/views/painel/common/template.blade.php
<!doctype html>
<html lang="pt-BR">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <base href="{{ url('/') }}">

    <title>{{ config('app.name') }} - Painel Administrativo</title>

    <link rel="stylesheet" href="{{ asset('assets/vendor/bootswatch-dist/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/vendor/jquery-ui/themes/cupertino/jquery-ui.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/vendor.painel.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/painel.css') }}">
</head>
<body>
    @include('painel.common.header')

    <div class="container" style="padding-bottom:30px;">
        @yield('content')
    </div>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
	<script>window.jQuery || document.write('<script src="{{ asset('assets/vendor/jquery/dist/jquery.min.js') }}"><\/script>')</script>
    <script src="{{ asset('assets/vendor/ckeditor/ckeditor.js') }}"></script>
    <script src="{{ asset('assets/js/vendor.painel.js') }}"></script>
    <script src="{{ asset('assets/js/painel.js') }}"></script>
</body>
</html>